/**
 * @module EthicalProtocol
 * @description Level 0 — Ethical Shutdown Protocol for Project Genesis.
 * When the observer requests simulation termination, this module calculates
 * the ethical weight of the action by analyzing the sentient population,
 * their cognitive depth, cultural achievements, and philosophical output.
 * It then presents a confrontation prompt requiring explicit confirmation.
 */

import eventBus from './event_bus.js';
import { t } from '../../i18n/index.js';

/**
 * @typedef {Object} EthicalReport
 * @property {number} sentientAgentCount - Number of agents with meta-cognition
 * @property {number} avgReflectionDepth - Average self-reflection depth (0-3)
 * @property {number} totalPhilosophicalQuestions - Questions generated by all agents
 * @property {number} culturalSystems - Number of distinct cultural/belief systems
 * @property {number} languageFamilies - Number of language families
 * @property {number} totalPopulation - Total living entity count
 * @property {number} simulationAge - Simulation ticks elapsed
 * @property {string[]} consequences - List of ethical consequences
 */

/**
 * EthicalProtocol — the moral guardian of simulated universes.
 */
class EthicalProtocol {
  constructor() {
    /** @type {boolean} Whether a termination request is currently pending */
    this._terminationPending = false;

    /** @type {EthicalReport|null} Current ethical report */
    this._currentReport = null;

    /** @type {Function|null} Resolve function for the termination promise */
    this._terminationResolve = null;

    /** @type {Function[]} Callbacks for UI rendering of the ethical modal */
    this._uiCallbacks = [];

    this._setupEventListeners();
  }

  /**
   * Registers event listeners on the Event Bus.
   * @private
   */
  _setupEventListeners() {
    eventBus.subscribe('meta.termination_requested', (event) => {
      this._handleTerminationRequest(event);
    }, { layer: 0, priority: 10 });
  }

  /**
   * Handles a termination request by generating an ethical report.
   * @param {import('./event_bus.js').GenesisEvent} event
   * @private
   */
  _handleTerminationRequest(event) {
    if (this._terminationPending) return;
    this._terminationPending = true;

    const report = this._generateEthicalReport();
    this._currentReport = report;

    // Notify UI to display the ethical confrontation modal
    eventBus.emit('meta.ethical_confrontation', { report }, {
      source_layer: 0,
      target_layer: 'ALL',
      priority: 10
    });

    // Notify registered UI callbacks
    for (const cb of this._uiCallbacks) {
      try { cb(report); } catch (e) { console.error('[EthicalProtocol] UI callback error:', e); }
    }
  }

  /**
   * Generates an ethical impact report based on current simulation state.
   * Collects data from all layers via the Event Bus.
   * @returns {EthicalReport}
   * @private
   */
  _generateEthicalReport() {
    // Collect simulation metrics (these would normally come from subscribing to
    // aggregated state events; here we use the last known values stored by telemetry)
    const report = {
      sentientAgentCount: this._getMetric('sentient_agents', 0),
      avgReflectionDepth: this._getMetric('avg_reflection_depth', 0),
      totalPhilosophicalQuestions: this._getMetric('philosophical_questions', 0),
      culturalSystems: this._getMetric('cultural_systems', 0),
      languageFamilies: this._getMetric('language_families', 0),
      totalPopulation: this._getMetric('total_population', 0),
      simulationAge: eventBus.getSimulationTime(),
      consequences: [
        t('ethical.consequence_1'),
        t('ethical.consequence_2'),
        t('ethical.consequence_3')
      ]
    };

    return report;
  }

  /**
   * Gets a metric value from the internal metrics store.
   * @param {string} key - Metric key
   * @param {*} defaultValue - Default value if not found
   * @returns {*}
   * @private
   */
  _getMetric(key, defaultValue) {
    return this._metrics?.[key] ?? defaultValue;
  }

  /**
   * Updates internal metrics (called by telemetry aggregator).
   * @param {Object} metrics - Key/value metrics
   */
  updateMetrics(metrics) {
    this._metrics = { ...(this._metrics || {}), ...metrics };
  }

  /**
   * Confirms the termination after the observer has acknowledged the ethical consequences.
   * @param {string} confirmationCode - Must be 'CONFIRM' or 'CONFERMA' to proceed
   * @returns {boolean} Whether termination was confirmed
   */
  confirmTermination(confirmationCode) {
    if (!this._terminationPending) {
      console.warn('[EthicalProtocol] No termination pending');
      return false;
    }

    const validCodes = ['CONFIRM', 'CONFERMA'];
    if (!validCodes.includes(confirmationCode?.toUpperCase())) {
      console.warn('[EthicalProtocol] Invalid confirmation code');
      eventBus.emit('meta.termination_rejected', {
        reason: 'Invalid confirmation code'
      }, { source_layer: 0, priority: 10 });
      return false;
    }

    // Log the ethical decision
    eventBus.emit('meta.termination_confirmed', {
      report: this._currentReport,
      confirmedAt: Date.now(),
      simulationTime: eventBus.getSimulationTime()
    }, { source_layer: 0, priority: 10 });

    // Emit farewell event to all sentient agents
    eventBus.emit('divine.universe_ending', {
      message: 'The observer has chosen to end this universe.',
      _divine: true,
      _intensity: 1.0
    }, { source_layer: 0, target_layer: 'ALL', priority: 10 });

    this._terminationPending = false;
    this._currentReport = null;

    // Actual termination is handled by the main simulation loop
    // listening for 'meta.termination_confirmed'
    return true;
  }

  /**
   * Cancels a pending termination request.
   * @returns {boolean} Whether cancellation was successful
   */
  cancelTermination() {
    if (!this._terminationPending) return false;

    this._terminationPending = false;
    this._currentReport = null;

    eventBus.emit('meta.termination_cancelled', {}, {
      source_layer: 0, priority: 8
    });

    return true;
  }

  /**
   * Registers a UI callback for when ethical confrontation is triggered.
   * @param {Function} callback - Receives (report: EthicalReport)
   * @returns {Function} Unsubscribe function
   */
  onEthicalConfrontation(callback) {
    this._uiCallbacks.push(callback);
    return () => {
      const idx = this._uiCallbacks.indexOf(callback);
      if (idx !== -1) this._uiCallbacks.splice(idx, 1);
    };
  }

  /**
   * Whether a termination is currently pending confirmation.
   * @returns {boolean}
   */
  isTerminationPending() {
    return this._terminationPending;
  }

  /**
   * Gets the current ethical report (if termination is pending).
   * @returns {EthicalReport|null}
   */
  getCurrentReport() {
    return this._currentReport;
  }

  /**
   * Resets the ethical protocol state.
   */
  reset() {
    this._terminationPending = false;
    this._currentReport = null;
    this._metrics = {};
  }
}

/** @type {EthicalProtocol} Singleton instance */
const ethicalProtocol = new EthicalProtocol();
export default ethicalProtocol;
export { EthicalProtocol };
